version: '3'

vars:
  BINARY: forge

tasks:
  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy

  test:
    cmds:
      - go test --cover ./...
      - go mod verify

  build:
    cmds:
      - go mod verify
      - goreleaser build --snapshot --clean --single-target

  install:
    vars:
      INSTALL_DIR: '{{.INSTALL_DIR | default "$HOME/.local/bin"}}'
    cmds:
      - task: build
      - mkdir -p {{.INSTALL_DIR}}
      - |
        # Find the goreleaser build output for current OS/arch
        BINARY_PATH=$(find dist -type f -name "{{.BINARY}}" ! -path "*/.*" | head -n 1)
        if [ -z "$BINARY_PATH" ]; then
          echo "Error: Could not find built binary in dist directory"
          exit 1
        fi
        cp "$BINARY_PATH" {{.INSTALL_DIR}}/{{.BINARY}}
      - chmod +x {{.INSTALL_DIR}}/{{.BINARY}}

  run:
    cmds:
      - task: build
      - ./bin/{{.BINARY}}

  clean:
    cmds:
      - rm -rf bin
      - rm -rf dist
