version: '3'

vars:
  BINARY: forge

tasks:
  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy

  test:
    cmds:
      - go test --cover ./...
      - go mod verify

  build:
    cmds:
      - go mod verify
      - goreleaser build --snapshot --clean --single-target

  install:
    cmds:
      - go install ./main.go

  run:
    cmds:
      - task: build
      - ./bin/{{.BINARY}}

  clean:
    cmds:
      - rm -rf bin
